// Password hashing for parity with the FastAPI bcrypt-based backend.
//
// Notes:
// - bcrypt in pure Deno runs on the main thread and is slow. We use the npm bcryptjs
//   package via the npm: specifier — it's portable, works in Edge Functions, and is
//   wire-compatible with bcrypt hashes generated by the Python `bcrypt` / passlib libs.
// - Existing hashes from the FastAPI backend (e.g. `$2b$12$...`) verify correctly.

import bcrypt from "npm:bcryptjs@2.4.3";

export async function hashPassword(plain: string): Promise<string> {
  const salt = await bcrypt.genSalt(12);
  return await bcrypt.hash(plain, salt);
}

export async function verifyPassword(
  plain: string,
  hashed: string,
): Promise<boolean> {
  try {
    return await bcrypt.compare(plain, hashed);
  } catch (_) {
    return false;
  }
}
